{
  "categories": [
    {
      "name": "Application Interfaces",
      "type_count": 6,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IAssemblyDoc",
        "SOLIDWORKS.Interop.sldworks.IDrawingDoc",
        "SOLIDWORKS.Interop.sldworks.IModelDoc2",
        "SOLIDWORKS.Interop.sldworks.IModelDocExtension",
        "SOLIDWORKS.Interop.sldworks.IPartDoc",
        "SOLIDWORKS.Interop.sldworks.ISldWorks"
      ]
    },
    {
      "name": "Annotation Interfaces",
      "type_count": 31,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IAnnotation",
        "SOLIDWORKS.Interop.sldworks.IAutoBalloonOptions",
        "SOLIDWORKS.Interop.sldworks.IBalloonOptions",
        "SOLIDWORKS.Interop.sldworks.IBalloonStack",
        "SOLIDWORKS.Interop.sldworks.ICenterLine",
        "SOLIDWORKS.Interop.sldworks.ICenterMark",
        "SOLIDWORKS.Interop.sldworks.ICThread",
        "SOLIDWORKS.Interop.sldworks.IDatumOrigin",
        "SOLIDWORKS.Interop.sldworks.IDatumTag",
        "SOLIDWORKS.Interop.sldworks.IDatumTargetSym",
        "SOLIDWORKS.Interop.sldworks.IDimensionTolerance",
        "SOLIDWORKS.Interop.sldworks.IDowelSymbol",
        "SOLIDWORKS.Interop.sldworks.IGtol",
        "SolidWorks.Interop.sldworks.IGtolFrame",
        "SOLIDWORKS.Interop.sldworks.IMagneticLine",
        "SOLIDWORKS.Interop.sldworks.IMultiJogLeader",
        "SOLIDWORKS.Interop.sldworks.INote",
        "SolidWorks.Interop.sldworks.IParagraphs",
        "SolidWorks.Interop.sldworks.IPMIDatumData",
        "SolidWorks.Interop.sldworks.IPMIDatumFeature",
        "SolidWorks.Interop.sldworks.IPMIDatumTarget",
        "SolidWorks.Interop.sldworks.IPMIDimensionData",
        "SolidWorks.Interop.sldworks.IPMIDimensionItem",
        "SolidWorks.Interop.sldworks.IPMIFrameData",
        "SolidWorks.Interop.sldworks.IPMIGtolBoxData",
        "SolidWorks.Interop.sldworks.IPMIGtolData",
        "SolidWorks.Interop.sldworks.IPMIGtolFrameDatum",
        "SOLIDWORKS.Interop.sldworks.IRevisionCloud",
        "SOLIDWORKS.Interop.sldworks.ISFSymbol",
        "SOLIDWORKS.Interop.sldworks.ISketchBlockDefinition",
        "SOLIDWORKS.Interop.sldworks.ISketchBlockInstance"
      ]
    },
    {
      "name": "Annotation Interfaces/IDisplayDimension",
      "type_count": 4,
      "types": [
        "SolidWorks.Interop.sldworks.ICalloutAngleVariable",
        "SolidWorks.Interop.sldworks.ICalloutLengthVariable",
        "SolidWorks.Interop.sldworks.ICalloutStringVariable",
        "SolidWorks.Interop.sldworks.ICalloutVariable"
      ]
    },
    {
      "name": "Annotation Interfaces/Table Annotations",
      "type_count": 13,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IBendTableAnnotation",
        "SOLIDWORKS.Interop.sldworks.IBomTableAnnotation",
        "SolidWorks.Interop.sldworks.IFamilyTableAnnotation",
        "SOLIDWORKS.Interop.sldworks.IGeneralTableAnnotation",
        "SolidWorks.Interop.sldworks.IGeneralToleranceTableAnnotation",
        "SOLIDWORKS.Interop.sldworks.IHoleTableAnnotation",
        "SOLIDWORKS.Interop.sldworks.IPunchTableAnnotation",
        "SOLIDWORKS.Interop.sldworks.IRevisionTableAnnotation",
        "SOLIDWORKS.Interop.sldworks.ITableAnnotation",
        "SOLIDWORKS.Interop.sldworks.ITitleBlockTableAnnotation",
        "SOLIDWORKS.Interop.sldworks.IWeldmentCutListAnnotation",
        "SOLIDWORKS.Interop.sldworks.IWeldBead",
        "SOLIDWORKS.Interop.sldworks.IWeldSymbol"
      ]
    },
    {
      "name": "Assembly Interfaces",
      "type_count": 11,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IAdvancedSelectionCriteria",
        "SolidWorks.Interop.sldworks.ICollision",
        "SolidWorks.Interop.sldworks.ICollisionDetectionGroup",
        "SolidWorks.Interop.sldworks.ICollisionDetectionManager",
        "SOLIDWORKS.Interop.sldworks.IComponent2",
        "SOLIDWORKS.Interop.sldworks.IDragOperator",
        "SOLIDWORKS.Interop.sldworks.IExplodeStep",
        "SolidWorks.Interop.sldworks.IGroundPlaneFeatureData",
        "SOLIDWORKS.Interop.sldworks.IInterference",
        "SOLIDWORKS.Interop.sldworks.IInterferenceDetectionMgr",
        "SolidWorks.Interop.sldworks.IMirrorComponentFeatureData"
      ]
    },
    {
      "name": "Assembly Interfaces/Mates",
      "type_count": 25,
      "types": [
        "SolidWorks.Interop.sldworks.IAngleMateFeatureData",
        "SolidWorks.Interop.sldworks.ICamFollowerMateFeatureData",
        "SolidWorks.Interop.sldworks.ICoincidentMateFeatureData",
        "SolidWorks.Interop.sldworks.IConcentricMateFeatureData",
        "SOLIDWORKS.Interop.sldworks.IDistance MateFeatureData",
        "SolidWorks.Interop.sldworks.IGearMateFeatureData",
        "SolidWorks.Interop.sldworks.IHingeMateFeatureData",
        "SolidWorks.Interop.sldworks.ILinearCouplerMateFeatureData",
        "SolidWorks.Interop.sldworks.ILockMateFeatureData",
        "SolidWorks.Interop.sldworks.IMate2",
        "SolidWorks.Interop.sldworks.IMateEntity2",
        "SolidWorks.Interop.sldworks.IMateFeatureData",
        "SolidWorks.Interop.sldworks.IMateInPlace",
        "SolidWorks.Interop.sldworks.IMateLoadReference",
        "SolidWorks.Interop.sldworks.IMateReference",
        "SolidWorks.Interop.sldworks.IParallelMateFeatureData",
        "SolidWorks.Interop.sldworks.IPerpendicularMateFeatureData",
        "SolidWorks.Interop.sldworks.IProfileCenterMateFeatureData",
        "SolidWorks.Interop.sldworks.IRackPinionMateFeatureData",
        "SolidWorks.Interop.sldworks.IScrewMateFeatureData",
        "SolidWorks.Interop.sldworks.ISlotMateFeatureData",
        "SolidWorks.Interop.sldworks.ISymmetricMateFeatureData",
        "SolidWorks.Interop.sldworks.ITangentMateFeatureData",
        "SolidWorks.Interop.sldworks.IUniversalJointMateFeatureData",
        "SolidWorks.Interop.sldworks.IWidthMateFeatureData"
      ]
    },
    {
      "name": "Configuration Interfaces",
      "type_count": 4,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IConfiguration",
        "SOLIDWORKS.Interop.sldworks.IConfigurationManager",
        "SOLIDWORKS.Interop.sldworks.IDesignTable",
        "SolidWorks.Interop.sldworks.IPartExplodeStep"
      ]
    },
    {
      "name": "Enumeration Interfaces",
      "type_count": 13,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IEnumBodies2",
        "SOLIDWORKS.Interop.sldworks.IEnumCoEdges",
        "SOLIDWORKS.Interop.sldworks.IEnumComponents2",
        "SOLIDWORKS.Interop.sldworks.IEnumDisplayDimensions",
        "SOLIDWORKS.Interop.sldworks.IEnumDocuments2",
        "SOLIDWORKS.Interop.sldworks.IEnumDrSections",
        "SOLIDWORKS.Interop.sldworks.IEnumEdges",
        "SOLIDWORKS.Interop.sldworks.IEnumFaces2",
        "SOLIDWORKS.Interop.sldworks.IEnumLoops2",
        "SOLIDWORKS.Interop.sldworks.IEnumModelViews",
        "SOLIDWORKS.Interop.sldworks.IEnumSketchHatches",
        "SOLIDWORKS.Interop.sldworks.IEnumSketchPoints",
        "SOLIDWORKS.Interop.sldworks.IEnumSketchSegments"
      ]
    },
    {
      "name": "Feature Interfaces",
      "type_count": 3,
      "types": [
        "SolidWorks.Interop.sldworks.IBeltChainFeatureData",
        "SOLIDWORKS.Interop.sldworks.IFeature",
        "SOLIDWORKS.Interop.sldworks.IFeatureManager"
      ]
    },
    {
      "name": "Feature Interfaces/Fillets",
      "type_count": 4,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IChamferFeatureData2",
        "SolidWorks.Interop.sldworks.IPartialEdgeFilletData",
        "SOLIDWORKS.Interop.sldworks.ISimpleFilletFeatureData2",
        "SOLIDWORKS.Interop.sldworks.IVariableFilletFeatureData2"
      ]
    },
    {
      "name": "Feature Interfaces/Folders",
      "type_count": 7,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IBodyFolder",
        "SOLIDWORKS.Interop.sldworks.IComment",
        "SOLIDWORKS.Interop.sldworks.ICommentFolder",
        "SOLIDWORKS.Interop.sldworks.ICosmeticWeldBeadFolder",
        "SOLIDWORKS.Interop.sldworks.IFeatureFolder",
        "SOLIDWORKS.Interop.sldworks.IFlatPatternFolder",
        "SOLIDWORKS.Interop.sldworks.ISheetMetalFolder"
      ]
    },
    {
      "name": "Feature Interfaces/Holes",
      "type_count": 10,
      "types": [
        "SolidWorks.Interop.sldworks.IAdvancedHoleElementData",
        "SolidWorks.Interop.sldworks.IAdvancedHoleFeatureData",
        "SolidWorks.Interop.sldworks.ICounterboreElementData",
        "SolidWorks.Interop.sldworks.ICountersinkElementData",
        "SOLIDWORKS.Interop.sldworks.IHoleSeriesFeatureData2",
        "SOLIDWORKS.Interop.sldworks.ISimpleHoleFeatureData2",
        "SolidWorks.Interop.sldworks.IStraightElementData",
        "SolidWorks.Interop.sldworks.IStraightTapElementData",
        "SolidWorks.Interop.sldworks.ITaperedTapElementData",
        "SOLIDWORKS.Interop.sldworks.IWizardHoleFeatureData2"
      ]
    },
    {
      "name": "Feature Interfaces/Lights and Cameras",
      "type_count": 2,
      "types": [
        "SOLIDWORKS.Interop.sldworks.ICamera",
        "SOLIDWORKS.Interop.sldworks.ILight"
      ]
    },
    {
      "name": "Feature Interfaces/Mold Tools",
      "type_count": 8,
      "types": [
        "SOLIDWORKS.Interop.sldworks.ICavityFeatureData",
        "SOLIDWORKS.Interop.sldworks.ICoreFeatureData",
        "SOLIDWORKS.Interop.sldworks.IMoveFaceFeatureData",
        "SOLIDWORKS.Interop.sldworks.IPartingLineFeatureData",
        "SOLIDWORKS.Interop.sldworks.IPartingSurfaceFeatureData",
        "SOLIDWORKS.Interop.sldworks.IRuledSurfaceFeatureData",
        "SOLIDWORKS.Interop.sldworks.IShutOffSurfaceFeatureData",
        "SOLIDWORKS.Interop.sldworks.IToolingSplitFeatureData"
      ]
    },
    {
      "name": "Feature Interfaces/Patterns and Mirroring",
      "type_count": 17,
      "types": [
        "SolidWorks.Interop.sldworks.IChainPatternFeatureData",
        "SOLIDWORKS.Interop.sldworks.ICircularPatternFeatureData",
        "SOLIDWORKS.Interop.sldworks.ICurveDrivenPatternFeatureData",
        "SOLIDWORKS.Interop.sldworks.IDerivedPatternFeatureData",
        "SolidWorks.Interop.sldworks.IDimPatternFeatureData",
        "SOLIDWORKS.Interop.sldworks.IFillPatternFeatureData",
        "SolidWorks.Interop.sldworks.IInstanceToVaryOptions",
        "SOLIDWORKS.Interop.sldworks.ILinearPatternFeatureData",
        "SOLIDWORKS.Interop.sldworks.ILocalCircularPatternFeatureData",
        "SOLIDWORKS.Interop.sldworks.ILocalCurvePatternFeatureData",
        "SolidWorks.Interop.sldworks.ILocalLinearPatternFeatureData",
        "SOLIDWORKS.Interop.sldworks.ILocalSketchPatternFeatureData",
        "SOLIDWORKS.Interop.sldworks.IMirrorPartFeatureData",
        "SOLIDWORKS.Interop.sldworks.IMirrorPatternFeatureData",
        "SOLIDWORKS.Interop.sldworks.IMirrorSolidFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISketchPatternFeatureData",
        "SOLIDWORKS.Interop.sldworks.ITablePatternFeatureData"
      ]
    },
    {
      "name": "Feature Interfaces/Reference Geometry",
      "type_count": 15,
      "types": [
        "SolidWorks.Interop.sldworks.IBoundingBoxFeatureData",
        "SOLIDWORKS.Interop.sldworks.ICompositeCurveFeatureData",
        "SOLIDWORKS.Interop.sldworks.IFreePointCurveFeatureData",
        "SOLIDWORKS.Interop.sldworks.IHelixFeatureData",
        "SOLIDWORKS.Interop.sldworks.IImportedCurveFeatureData",
        "SOLIDWORKS.Interop.sldworks.IProjectionCurveFeatureData",
        "SOLIDWORKS.Interop.sldworks.IRefAxis",
        "SOLIDWORKS.Interop.sldworks.IRefAxisFeatureData",
        "SOLIDWORKS.Interop.sldworks.IReferenceCurve",
        "SOLIDWORKS.Interop.sldworks.IReferencePointCurveFeatureData",
        "SOLIDWORKS.Interop.sldworks.IRefPlane",
        "SOLIDWORKS.Interop.sldworks.IRefPlaneFeatureData",
        "SOLIDWORKS.Interop.sldworks.IRefPoint",
        "SOLIDWORKS.Interop.sldworks.IRefPointFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISplitLineFeatureData"
      ]
    },
    {
      "name": "Feature Interfaces/Sheet Metal",
      "type_count": 25,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IBaseFlangeFeatureData",
        "SOLIDWORKS.Interop.sldworks.IBendsFeatureData",
        "SOLIDWORKS.Interop.sldworks.IBreakCornerFeatureData",
        "SOLIDWORKS.Interop.sldworks.IClosedCornerFeatureData",
        "SolidWorks.Interop.sldworks.IConvertSolidFeatureData",
        "SolidWorks.Interop.sldworks.ICornerReliefFeatureData",
        "SolidWorks.Interop.sldworks.ICrossBreakFeatureData",
        "SOLIDWORKS.Interop.sldworks.ICustomBendAllowance",
        "SOLIDWORKS.Interop.sldworks.IEdgeFlangeFeatureData",
        "SOLIDWORKS.Interop.sldworks.IFlatPatternFeatureData",
        "SOLIDWORKS.Interop.sldworks.IFoldsFeatureData",
        "SOLIDWORKS.Interop.sldworks.IHemFeatureData",
        "SOLIDWORKS.Interop.sldworks.IJogFeatureData",
        "SOLIDWORKS.Interop.sldworks.ILoftedBendsFeatureData",
        "SOLIDWORKS.Interop.sldworks.IMiterFlangeFeatureData",
        "SOLIDWORKS.Interop.sldworks.IOneBendFeatureData",
        "SOLIDWORKS.Interop.sldworks.IRipFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISheetMetalFeatureData",
        "SolidWorks.Interop.sldworks.ISheetMetalGaugeTableParameters",
        "SOLIDWORKS.Interop.sldworks.ISketchedBendFeatureData",
        "SolidWorks.Interop.sldworks.ISMCornerReliefData",
        "SOLIDWORKS.Interop.sldworks.ISMGussetFeatureData",
        "SolidWorks.Interop.sldworks.ISMNormalCutFeatureData2",
        "SolidWorks.Interop.sldworks.ISMNormalCutGroupData",
        "SolidWorks.Interop.sldworks.ISweptFlangeFeatureData"
      ]
    },
    {
      "name": "Feature Interfaces/Structure Systems",
      "type_count": 21,
      "types": [
        "SolidWorks.Interop.sldworks.IComplexCornerTreatmentFeatureData",
        "SolidWorks.Interop.sldworks.ICornerManagementFolder",
        "SolidWorks.Interop.sldworks.ICornerMember",
        "SolidWorks.Interop.sldworks.ICornerTreatmentFeatureData",
        "SolidWorks.Interop.sldworks.ICornerTreatmentGroupFolder",
        "SolidWorks.Interop.sldworks.IPrimaryMemberFacePlaneIntersectionFeatureData",
        "SolidWorks.Interop.sldworks.IPrimaryMemberPathSegmentFeatureData",
        "SolidWorks.Interop.sldworks.IPrimaryMemberPointLengthFeatureData",
        "SolidWorks.Interop.sldworks.IPrimaryMemberRefPlaneFeatureData",
        "SolidWorks.Interop.sldworks.IPrimaryStructuralMemberFeatureData",
        "SolidWorks.Interop.sldworks.IProfileGroupFolder",
        "SolidWorks.Interop.sldworks.ISecondaryMemberBetweenPointsFeatureData",
        "SolidWorks.Interop.sldworks.ISecondaryMemberSupportPlaneFeatureData",
        "SolidWorks.Interop.sldworks.ISecondaryMemberUpToMembersFeatureData",
        "SolidWorks.Interop.sldworks.ISecondaryStructuralMemberFeatureData",
        "SolidWorks.Interop.sldworks.ISimpleCornerTreatmentFeatureData",
        "SolidWorks.Interop.sldworks.IStructureSystemFolder",
        "SolidWorks.Interop.sldworks.IStructureSystemMemberFeatureData",
        "SolidWorks.Interop.sldworks.IStructureSystemMemberProfile",
        "SolidWorks.Interop.sldworks.IStructureSystemSplitMember",
        "SolidWorks.Interop.sldworks.ITwoMemberCornerTreatmentFeatureData"
      ]
    },
    {
      "name": "Feature Interfaces/Surfaces",
      "type_count": 14,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IDeleteFaceFeatureData",
        "SOLIDWORKS.Interop.sldworks.IFillSurfaceFeatureData",
        "SOLIDWORKS.Interop.sldworks.IReplaceFaceFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISurfaceCutFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISurfaceExtendFeatureData",
        "SolidWorks.Interop.sldworks.ISurfaceFlattenFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISurfaceKnitFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISurfaceOffsetFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISurfacePlanarFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISurfaceRadiateFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISurfaceTrimFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISurfExtrudeFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISurfRevolveFeatureData",
        "SOLIDWORKS.Interop.sldworks.IThickenFeatureData"
      ]
    },
    {
      "name": "Feature Interfaces/Threads",
      "type_count": 1,
      "types": [
        "SolidWorks.Interop.sldworks.IThreadFeatureData"
      ]
    },
    {
      "name": "Feature Interfaces/Views",
      "type_count": 1,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IBrokenOutSectionFeatureData"
      ]
    },
    {
      "name": "Feature Interfaces/Weldments",
      "type_count": 7,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IEndCapFeatureData",
        "SOLIDWORKS.Interop.sldworks.IGussetFeatureData",
        "SOLIDWORKS.Interop.sldworks.IStructuralMemberFeatureData",
        "SOLIDWORKS.Interop.sldworks.IStructuralMemberGroup",
        "SOLIDWORKS.Interop.sldworks.IWeldmentBeadFeatureData",
        "SOLIDWORKS.Interop.sldworks.IWeldmentCutListFeature",
        "SOLIDWORKS.Interop.sldworks.IWeldmentTrimExtendFeatureData"
      ]
    },
    {
      "name": "Feature Interfaces/Others",
      "type_count": 32,
      "types": [
        "SolidWorks.Interop.sldworks.IBoundaryBossFeatureData",
        "SOLIDWORKS.Interop.sldworks.ICombineBodiesFeatureData",
        "SolidWorks.Interop.sldworks.ICoordinateSystemElement",
        "SOLIDWORKS.Interop.sldworks.ICoordinateSystemFeatureData",
        "SOLIDWORKS.Interop.sldworks.ICosmeticThreadFeatureData",
        "SOLIDWORKS.Interop.sldworks.ICosmeticWeldBeadFeatureData",
        "SOLIDWORKS.Interop.sldworks.IDeleteBodyFeatureData",
        "SOLIDWORKS.Interop.sldworks.IDerivedPartFeatureData",
        "SOLIDWORKS.Interop.sldworks.IDomeFeatureData2",
        "SOLIDWORKS.Interop.sldworks.IDraftFeatureData2",
        "SOLIDWORKS.Interop.sldworks.IExtrudeFeatureData2",
        "SOLIDWORKS.Interop.sldworks.IFeatureStatistics",
        "SOLIDWORKS.Interop.sldworks.IHealEdgesFeatureData",
        "SolidWorks.Interop.sldworks.IIndentFeatureData",
        "SOLIDWORKS.Interop.sldworks.IIntersectFeatureData",
        "SOLIDWORKS.Interop.sldworks.IJoinFeatureData",
        "SOLIDWORKS.Interop.sldworks.ILibraryFeatureData",
        "SolidWorks.Interop.sldworks.ILibraryFormToolFeatureData",
        "SOLIDWORKS.Interop.sldworks.ILoftFeatureData",
        "SOLIDWORKS.Interop.sldworks.IMacroFeatureData",
        "SOLIDWORKS.Interop.sldworks.IMoveCopyBodyFeatureData",
        "SOLIDWORKS.Interop.sldworks.IRevolveFeatureData2",
        "SOLIDWORKS.Interop.sldworks.IRibFeatureData2",
        "SOLIDWORKS.Interop.sldworks.ISaveBodyFeatureData",
        "SOLIDWORKS.Interop.sldworks.IScaleFeatureData",
        "SOLIDWORKS.Interop.sldworks.IShellFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISketchPicture",
        "SOLIDWORKS.Interop.sldworks.ISplitBodyFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISweepFeatureData",
        "SolidWorks.Interop.sldworks.ITabAndSlotFeatureData",
        "SolidWorks.Interop.sldworks.ITabAndSlotGroupData",
        "SOLIDWORKS.Interop.sldworks.IWrapSketchFeatureData"
      ]
    },
    {
      "name": "Model Interfaces",
      "type_count": 22,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IAnnotationView",
        "SOLIDWORKS.Interop.sldworks.IAttribute",
        "SOLIDWORKS.Interop.sldworks.IAttributeDef",
        "SOLIDWORKS.Interop.sldworks.IBody2",
        "SOLIDWORKS.Interop.sldworks.ICoEdge",
        "SOLIDWORKS.Interop.sldworks.ICurve",
        "SOLIDWORKS.Interop.sldworks.IDimension",
        "SOLIDWORKS.Interop.sldworks.IEdge",
        "SOLIDWORKS.Interop.sldworks.IEdgePoint",
        "SOLIDWORKS.Interop.sldworks.IEntity",
        "SOLIDWORKS.Interop.sldworks.IFace2",
        "SolidWorks.Interop.sldworks.IFacet",
        "SolidWorks.Interop.sldworks.IGraphicsBody",
        "SOLIDWORKS.Interop.sldworks.ILoop2",
        "SolidWorks.Interop.sldworks.IMeshBody",
        "SOLIDWORKS.Interop.sldworks.IMidSurface3",
        "SOLIDWORKS.Interop.sldworks.IModeler",
        "SOLIDWORKS.Interop.sldworks.IParameter",
        "SOLIDWORKS.Interop.sldworks.ISectionViewData",
        "SOLIDWORKS.Interop.sldworks.ISpring",
        "SOLIDWORKS.Interop.sldworks.ISurface",
        "SOLIDWORKS.Interop.sldworks.IVertex"
      ]
    },
    {
      "name": "Motion Studies",
      "type_count": 17,
      "types": [
        "SOLIDWORKS.Interop.swmotionstudy.IAVIParameter",
        "SOLIDWORKS.Interop.swmotionstudy.ICosmosMotionStudyProperties",
        "SOLIDWORKS.Interop.swmotionstudy.ICosmosMotionStudyResults",
        "SOLIDWORKS.Interop.sldworks.IMotionPlotAxisFeatureData",
        "SOLIDWORKS.Interop.sldworks.IMotionPlotFeatureData",
        "SOLIDWORKS.Interop.swmotionstudy.IMotionPlotFeatureOutput",
        "SOLIDWORKS.Interop.swmotionstudy.IMotionStudy",
        "SOLIDWORKS.Interop.swmotionstudy.IMotionStudyManager",
        "SOLIDWORKS.Interop.swmotionstudy.IMotionStudyProperties",
        "SOLIDWORKS.Interop.swmotionstudy.IMotionStudyResults",
        "SOLIDWORKS.Interop.swmotionstudy.IPhysicalSimulationMotionStudyProperties",
        "SOLIDWORKS.Interop.sldworks.ISimulation3DContactFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISimulationDamperFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISimulationForceFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISimulationGravityFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISimulationMotorFeatureData",
        "SOLIDWORKS.Interop.sldworks.ISimulationSpringFeatureData"
      ]
    },
    {
      "name": "Sketch",
      "type_count": 20,
      "types": [
        "SOLIDWORKS.Interop.sldworks.ISketch",
        "SOLIDWORKS.Interop.sldworks.ISketchArc",
        "SOLIDWORKS.Interop.sldworks.ISketchBlockDefinition",
        "SOLIDWORKS.Interop.sldworks.ISketchBlockInstance",
        "SOLIDWORKS.Interop.sldworks.ISketchContour",
        "SOLIDWORKS.Interop.sldworks.ISketchEllipse",
        "SOLIDWORKS.Interop.sldworks.ISketchHatch",
        "SOLIDWORKS.Interop.sldworks.ISketchLine",
        "SOLIDWORKS.Interop.sldworks.ISketchManager",
        "SOLIDWORKS.Interop.sldworks.ISketchParabola",
        "SOLIDWORKS.Interop.sldworks.ISketchPath",
        "SOLIDWORKS.Interop.sldworks.ISketchPoint",
        "SOLIDWORKS.Interop.sldworks.ISketchRegion",
        "SOLIDWORKS.Interop.sldworks.ISketchRelation",
        "SOLIDWORKS.Interop.sldworks.ISketchRelationManager",
        "SOLIDWORKS.Interop.sldworks.ISketchSegment",
        "SOLIDWORKS.Interop.sldworks.ISketchSlot",
        "SOLIDWORKS.Interop.sldworks.ISketchSpline",
        "SOLIDWORKS.Interop.sldworks.ISketchText",
        "SOLIDWORKS.Interop.sldworks.ISplineHandle"
      ]
    },
    {
      "name": "Utility Interfaces",
      "type_count": 45,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IBomTableSortData",
        "SOLIDWORKS.Interop.sldworks.IBSurfParamData",
        "SOLIDWORKS.Interop.sldworks.IColorTable",
        "SOLIDWORKS.Interop.sldworks.ICurveParamData",
        "SOLIDWORKS.Interop.sldworks.ICustomPropertyManager",
        "SolidWorks.Interop.sldworks.ICutListItem",
        "SolidWorks.Interop.sldworks.ICutListSortOptions",
        "SOLIDWORKS.Interop.sldworks.IDiagnoseResult",
        "SOLIDWORKS.Interop.sldworks.IDisplayData",
        "SOLIDWORKS.Interop.sldworks.IDocumentSpecification",
        "SOLIDWORKS.Interop.sldworks.IEnvironment",
        "SOLIDWORKS.Interop.sldworks.IEquationMgr",
        "SOLIDWORKS.Interop.sldworks.IExportPdfData",
        "SOLIDWORKS.Interop.sldworks.IFaultEntity",
        "SolidWorks.Interop.sldworks.IHoleDataTable",
        "SolidWorks.Interop.sldworks.IHoleStandardsData",
        "SolidWorks.Interop.sldworks.IImport3DInterconnectData",
        "SOLIDWORKS.Interop.sldworks.IImportDxfDwgData",
        "SolidWorks.Interop.sldworks.IImportIgesData",
        "SOLIDWORKS.Interop.sldworks.IImportStepData",
        "SOLIDWORKS.Interop.sldworks.IManipulator",
        "SolidWorks.Interop.sldworks.IMassProperty2",
        "SolidWorks.Interop.sldworks.IMassPropertyOverrideOptions",
        "SOLIDWORKS.Interop.sldworks.IMathPoint",
        "SOLIDWORKS.Interop.sldworks.IMathTransform",
        "SOLIDWORKS.Interop.sldworks.IMathUtility",
        "SOLIDWORKS.Interop.sldworks.IMathVector",
        "SOLIDWORKS.Interop.sldworks.IMeasure",
        "SOLIDWORKS.Interop.sldworks.IPageSetup",
        "SolidWorks.Interop.sldworks.IPLMObjectSpecification",
        "SOLIDWORKS.Interop.sldworks.IPrintSpecification",
        "SOLIDWORKS.Interop.sldworks.ISafeArrayUtility",
        "SolidWorks.Interop.sldworks.ISaveTo3DExperienceOptions",
        "SolidWorks.Interop.swscanto3d.IScanto3D",
        "SOLIDWORKS.Interop.sldworks.ISelectData",
        "SOLIDWORKS.Interop.sldworks.ISelectionMgr",
        "SolidWorks.Interop.sldworks.ISlicingData",
        "SOLIDWORKS.Interop.dsgnchk.ISWDesignCheck",
        "SOLIDWORKS.Interop.sldworks.ISplineParamData",
        "SOLIDWORKS.Interop.sldworks.ISurfaceParameterizationData",
        "SOLIDWORKS.Interop.sldworks.ISwOLEObject",
        "SOLIDWORKS.Interop.sldworks.ITessellation",
        "SOLIDWORKS.Interop.sldworks.ITextFormat",
        "SOLIDWORKS.Interop.sldworks.ITexture",
        "SOLIDWORKS.Interop.sldworks.IUserUnit"
      ]
    },
    {
      "name": "User-interface Interfaces/Appearances and Decals",
      "type_count": 7,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IAppearanceSetting",
        "SOLIDWORKS.Interop.sldworks.IDecal",
        "SolidWorks.Interop.sldworks.IDSPBRMaterial",
        "SOLIDWORKS.Interop.sldworks.IFaceDecalProperties",
        "SOLIDWORKS.Interop.sldworks.IRayTraceRenderer",
        "SOLIDWORKS.Interop.sldworks.IRayTraceRendererOptions",
        "SOLIDWORKS.Interop.sldworks.IRenderMaterial"
      ]
    },
    {
      "name": "User-interface Interfaces",
      "type_count": 25,
      "types": [
        "SOLIDWORKS.Interop.sldworks.ICallout",
        "SOLIDWORKS.Interop.sldworks.IDisplayStateSetting",
        "SOLIDWORKS.Interop.sldworks.IDragArrowManipulator",
        "SOLIDWORKS.Interop.sldworks.IFeatMgrView",
        "SOLIDWORKS.Interop.sldworks.IFrame",
        "SolidWorks.Interop.sldworks.ILightDialog",
        "SOLIDWORKS.Interop.sldworks.IMaterialVisualPropertiesData",
        "SolidWorks.Interop.sldworks.IMessageBarDefinition",
        "SOLIDWORKS.Interop.sldworks.IModelView",
        "SOLIDWORKS.Interop.sldworks.IModelViewManager",
        "SOLIDWORKS.Interop.sldworks.IModelWindow",
        "SOLIDWORKS.Interop.sldworks.IMouse",
        "SOLIDWORKS.Interop.sldworks.IPackAndGo",
        "SOLIDWORKS.Interop.sldworks.IPlaneManipulator",
        "SOLIDWORKS.Interop.sldworks.IPrint3DDialog",
        "SolidWorks.Interop.sldworks.IRenamedDocumentReferences",
        "SOLIDWORKS.Interop.sldworks.ISnapShot",
        "SOLIDWORKS.Interop.sldworks.IStatusBarPane",
        "SOLIDWORKS.Interop.swhtmlcontrol.ISwHtmlInterface",
        "SOLIDWORKS.Interop.sldworks.ISWPropertySheet",
        "SOLIDWORKS.Interop.sldworks.ITaskpaneView",
        "SOLIDWORKS.Interop.sldworks.ITreeControlItem",
        "SOLIDWORKS.Interop.sldworks.ITriadManipulator",
        "SolidWorks.Interop.sldworks.IUserNotificationDefinition",
        "SOLIDWORKS.Interop.sldworks.IUserProgressBar"
      ]
    },
    {
      "name": "User-interface Interfaces/CommandManager",
      "type_count": 5,
      "types": [
        "SOLIDWORKS.Interop.sldworks.ICommandGroup",
        "SOLIDWORKS.Interop.sldworks.ICommandManager",
        "SOLIDWORKS.Interop.sldworks.ICommandTab",
        "SOLIDWORKS.Interop.sldworks.ICommandTabBox",
        "SOLIDWORKS.Interop.sldworks.IFlyoutGroup"
      ]
    },
    {
      "name": "User-interface Interfaces/PropertyManager",
      "type_count": 18,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPage2",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageActiveX",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageBitmap",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageBitmapButton",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageButton",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageCheckbox",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageCombobox",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageControl",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageGroup",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageLabel",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageListbox",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageNumberbox",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageOption",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageSelectionbox",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageSlider",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageTab",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageTextbox",
        "SOLIDWORKS.Interop.sldworks.IPropertyManagerPageWindowFromHandle"
      ]
    },
    {
      "name": "User-interface Interfaces/Selection Sets",
      "type_count": 3,
      "types": [
        "SolidWorks.Interop.sldworks.ISelectionSet",
        "SolidWorks.Interop.sldworks.ISelectionSetFolder",
        "SolidWorks.Interop.sldworks.ISelectionSetItem"
      ]
    },
    {
      "name": "User-interface Interfaces/Sensors",
      "type_count": 2,
      "types": [
        "SOLIDWORKS.Interop.sldworks.IDimensionSensorData",
        "SOLIDWORKS.Interop.sldworks.ISensor"
      ]
    },
    {
      "name": "User-interface Interfaces/SOLIDWORKS MBD 3D PDF",
      "type_count": 2,
      "types": [
        "SolidWorks.Interop.sldworks.IMBD3DPdfData",
        "SolidWorks.Interop.sldworks.ITextAndCustomProperty"
      ]
    },
    {
      "name": "Custom Interfaces",
      "type_count": 16,
      "types": [
        "SolidWorks.Interop.swpublished.IMessageBarHandler",
        "SOLIDWORKS.Interop.swpublished.IPropertyManagerPage2Handler9",
        "SOLIDWORKS.Interop.sw3dprinter.ISw3DPrinter",
        "SOLIDWORKS.Interop.swpublished.ISwCalloutHandler",
        "SOLIDWORKS.Interop.swpublished.ISwAddin",
        "SOLIDWORKS.Interop.swpublished.ISwAddinBroker",
        "SOLIDWORKS.Interop.swpublished.ISwColorContour1",
        "SOLIDWORKS.Interop.swpublished.ISwComFeature",
        "SOLIDWORKS.Interop.swpublished.ISwManipulatorHandler2",
        "SolidWorks.Interop.sldworks.ISwPEClassFactory",
        "SOLIDWORKS.Interop.swpublished.ISwPEManager",
        "SolidWorks.Interop.sldworks.ISwPEToken",
        "SOLIDWORKS.Interop.swpublished.ISwQuickTip",
        "SolidWorks.Interop.sldworks.ISwScene",
        "SOLIDWORKS.Interop.swpublished.ISwUndoAPIHandler",
        "SolidWorks.Interop.swpublished.IUserNotificationHandler"
      ]
    }
  ],
  "total_categories": 35,
  "total_types": 456
}